version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.0
    - 5.22.0
    - 5.26.2
    - 5.27.0
    - 5.27.1
    - 5.27.2
    - 5.31.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.35.0
    - 5.36.0
  - dependency-name: css-loader
    versions:
    - 5.1.4
    - 5.2.2
  - dependency-name: underscore
    versions:
    - 1.13.0
  - dependency-name: chai
    versions:
    - 4.3.2
